// © 2025 Nexus Macro Strategy
// @version=6
strategy("Nexus Macro Strategy [V1]", overlay=true, initial_capital=10000)

lookback = input.int(100, "Lookback")
float h = ta.highest(high, lookback)
float l = ta.lowest(low, lookback)

if ta.change(h) > 0
    strategy.entry("Short", strategy.short, limit=h - ta.atr(14))
if ta.change(l) < 0
    strategy.entry("Long", strategy.long, limit=l + ta.atr(14))
